### ISSUE TITLE
Замечания по паттерну "Наблюдатель"

### ISSUE THREAD

**Issue by alexey-malov** [protasov-ilja/OOD#2]
- [x] Упростить метод RemoveObserver

**Comment by iandreyshev** [comment]
- [ ] Избавиться от рефлешкена в классе SStatsDisplay

**Comment by alexey-malov** [comment]
- [x] CStatisticalDataOfAngles - надо более адекватное имя. В терминах предметной области

- [x] Зачем в CStatisticalDataOfAngles нужен метод SetWindSpeed()? Что если мы его вызовем после Accumulate? Вообще, адекватно ли адекватно ли этому классу реализовывать интерфейс IStatisticalData? В случае с ветром, в метод Update следует передавать 2 параметра - скорость и направление. А имя data - слишком неконкретное

- [x] Избавиться от приведения типа вниз по иерархии в методе CStatisDispaly::Update()

- [x] Какой смысл в методе CStatisDisplay::DisplayValue?
